name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
    - name: Install gcc
      run: mingw-get install gcc
    - name: Install ncurses
      run: mingw-get install ncurses
    - name: Build and run
      run: gcc main.c -o main -lpdcurses && main
