name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
    - name: Buid and run
      run: dir
    
  
