name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
    - name: Open Workflow Project
      run: cd ${{ github.workspace }}
    - name: List directories
      run: dir ${{ github.workspace }}
    - name: Get GCC Version
      run: gcc --version